task :default => ['test:all']
task :test => :default
namespace 'test' do

  desc 'test all'
  task :all => [:testNumberWords, :testFizzBuzz, :testSoftWrap]


  desc 'test numberWords'
  task :testNumberWords do
    ruby 'spec/numberWords_spec.rb'
  end

  desc 'test fizzBuzz'
  task :testFizzBuzz do
    ruby 'spec/FizzBuzz_spec.rb'
  end

  desc 'test softWrap'
  task :testSoftWrap do
    ruby 'spec/SoftWrap_spec.rb'
  end

end
